# Generated by Django 3.2.18 on 2023-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishanalysis',
            name='analysis_type',
            field=models.IntegerField(choices=[(0, '偵測'), (1, '計數')], default=0, verbose_name='分析類型'),
        ),
    ]
