# Generated by Django 3.2.18 on 2023-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishData', '0002_alter_fishanalysis_analysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('DE', '偵測'), ('CO', '計數')], default='DE', max_length=2, verbose_name='分析類型'),
        ),
    ]
