# Generated by Django 3.2.18 on 2023-04-18 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FishData', '0004_rename_can_anaylze_fishanalysis_can_analyze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishdetection',
            name='frame',
        ),
        migrations.AddField(
            model_name='fishdetection',
            name='detect_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='偵測時間'),
            preserve_default=False,
        ),
    ]
