# Generated by Django 4.2.1 on 2023-05-16 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishData', '0005_auto_20230418_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetection',
            name='detect_time',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), verbose_name='偵測時間'),
        ),
    ]
