# Generated by Django 4.2.1 on 2023-05-25 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FishData', '0006_FishData'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetection',
            name='detect_time',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), help_text='幾時幾分幾秒進行這次偵測？', verbose_name='偵測時間'),
        ),
    ]
