# Generated by Django 4.2.1 on 2023-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FishData', '0007_alter_fishdetection_detect_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerainfo',
            name='frame_rate',
        ),
        migrations.RemoveField(
            model_name='camerainfo',
            name='resolution',
        ),
    ]
