# Generated by Django 4.2.3 on 2023-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpage',
            name='test_text',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
