# Generated by Django 3.2.18 on 2023-04-08 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='CommonPage',
        ),
    ]
