# Generated by Django 3.2.18 on 2023-04-09 05:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_homepage_commonpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(blank=True, form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('demo', wagtail.blocks.StructBlock([('iframe', wagtail.blocks.CharBlock(blank=True, help_text='iframe url', max_length=100)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('topic', wagtail.blocks.CharBlock(blank=True)), ('description', wagtail.blocks.RichTextBlock())], help_text='Use either iframe or photo')), ('gallery', wagtail.blocks.StructBlock([('photo1', wagtail.images.blocks.ImageChooserBlock()), ('photo2', wagtail.images.blocks.ImageChooserBlock()), ('photo_big', wagtail.images.blocks.ImageChooserBlock())])), ('dashboard', wagtail.blocks.CharBlock(blank=True, helper_text='dash app', max_length=50))], blank=True, use_json_field=True),
        ),
    ]
