# Generated by Django 4.2.3 on 2023-07-30 05:40

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_commonpage_test_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commonpage',
            name='test_text',
        ),
        migrations.AlterField(
            model_name='commonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(blank=True, form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('demo', wagtail.blocks.StructBlock([('iframe', wagtail.blocks.URLBlock(blank=True, help_text='iframe url', max_length=100, required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('topic', wagtail.blocks.CharBlock(blank=True)), ('description', wagtail.blocks.RichTextBlock())], help_text='Use either iframe or photo')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), help_text='This is designed for **2 to 6** images')), ('dashboard', wagtail.blocks.CharBlock(blank=True, helper_text='dash app', max_length=50))], blank=True, use_json_field=True),
        ),
    ]
