# Generated by Django 4.2.3 on 2023-07-30 06:04

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_genericpagecontent_remove_commonpage_test_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericpagecontent',
            options={'verbose_name': '頁首與頁尾'},
        ),
        migrations.RemoveField(
            model_name='genericpagecontent',
            name='test_text',
        ),
        migrations.AddField(
            model_name='genericpagecontent',
            name='copyright_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='genericpagecontent',
            name='footer_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='頁尾底色', max_length=7),
        ),
    ]
