# Generated by Django 4.2.3 on 2023-07-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0004_alter_genericpagecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpagecontent',
            name='banner_image',
            field=models.ForeignKey(help_text='頁首底圖', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
