# Generated by Django 4.2.3 on 2023-07-30 06:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0005_genericpagecontent_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpagecontent',
            old_name='banner_image',
            new_name='banner_bg_image',
        ),
        migrations.RemoveField(
            model_name='genericpagecontent',
            name='footer_bg_color',
        ),
        migrations.AddField(
            model_name='genericpagecontent',
            name='banner_bg_tint',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='頁首', max_length=7),
        ),
        migrations.AddField(
            model_name='genericpagecontent',
            name='footer_bg_image',
            field=models.ForeignKey(help_text='頁首底圖', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='genericpagecontent',
            name='footer_bg_tint',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='頁尾', max_length=7),
        ),
    ]
