# Generated by Django 4.2.3 on 2023-07-31 15:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0006_rename_banner_image_genericpagecontent_banner_bg_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpagecontent',
            name='copyright_info',
        ),
        migrations.RemoveField(
            model_name='genericpagecontent',
            name='footer_bg_image',
        ),
        migrations.RemoveField(
            model_name='genericpagecontent',
            name='footer_bg_tint',
        ),
        migrations.AlterField(
            model_name='genericpagecontent',
            name='banner_bg_image',
            field=models.ForeignKey(blank=True, help_text='頁首底圖', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='genericpagecontent',
            name='banner_bg_tint',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='頁首色調', max_length=7),
        ),
    ]
