# Generated by Django 4.2.1 on 2023-05-25 08:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_commonpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='commonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(blank=True, form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('demo', wagtail.blocks.StructBlock([('iframe', wagtail.blocks.CharBlock(blank=True, help_text='iframe url', max_length=100, required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('topic', wagtail.blocks.CharBlock(blank=True)), ('description', wagtail.blocks.RichTextBlock())], help_text='Use either iframe or photo')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), help_text='This is designed for **2 to 6** images')), ('dashboard', wagtail.blocks.CharBlock(blank=True, helper_text='dash app', max_length=50))], blank=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.commonpage')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
