# Generated by Django 4.2.1 on 2023-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_menu_alter_commonpage_body_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AddField(
            model_name='menu',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
