# Generated by Django 4.2.1 on 2023-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_menu_slug_remove_menuitem_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
